### ISSUE TITLE
Windows / Python 3.5 install error

### ISSUE THREAD

**Issue by richardotis** [conda-forge/hdf5-feedstock#27] opened 2016-07-19 19:36 UTC
```
Error: ERROR: placeholder 'C:/conda/envs/_build' too short in: hdf5-1.8.17-vc14_2
```

Full log: https://ci.appveyor.com/project/richardotis/pycalphad/build/job/73xit3tebehokwsf

**Comment by jakirkham** [comment] 2016-07-19 19:42
I'm almost certain that this is ours, but could you please add `conda config --set show_channel_urls true` before that install. That way we can confirm it is coming from our channel.

**Comment by jakirkham** [comment] 2016-07-19 19:43
@gillins, could you please look at this when you have a chance?

**Comment by richardotis** [comment] 2016-07-19 20:23
In this case the default channel only has 1.8.16 and my channel doesn't have hdf5, but I will follow that rule when reporting issues in the future.

**Comment by gillins** [comment] 2016-07-19 23:55
I haven't managed to reproduce this on my Windows VM. I've tried installing all the same packages. @richardotis have you seen the same error locally? I'm wondering if it is something specific to AppVeyor. Are you using a different version of `conda-build` from the default?

**Comment by richardotis** [comment] 2016-07-20 02:11
It will take me some time for me to get a local Windows machine. The version of `conda-build` is the version that ships with `Miniconda3-3.19.0-Windows-x86_64.exe`, which is an older version of the installer I pinned to work around a miniconda bug.

**Comment by gillins** [comment] 2016-07-20 02:28
What was the bug you are trying to work around? I wonder if we are seeing a bug in the older version which may have since been fixed...

**Comment by rsignell-usgs** [comment] 2016-07-22 19:05
I'm getting the same problem here:
```
[Miniconda3] C:\Users\rsignell\documents\github>conda create -n netcdf4 python=3
 netcdf4
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment C:\Users\rsignell\AppData\Local\Con
tinuum\Miniconda3\envs\netcdf4:

The following NEW packages will be INSTALLED:

    certifi:      2016.2.28-py35_1  conda-forge
    curl:         7.49.0-vc14_0     defaults    [vc14]
    hdf4:         4.2.11-vc14_4     conda-forge [vc14]
    hdf5:         1.8.17-vc14_2     conda-forge [vc14]
    jpeg:         9b-vc14_0         conda-forge [vc14]
    libnetcdf:    4.4.0-vc14_1      conda-forge [vc14]
    mkl:          11.3.3-1          defaults
    netcdf4:      1.2.4-np111py35_2 conda-forge
    numpy:        1.11.1-py35_0     defaults
    pip:          8.1.2-py35_0      conda-forge
    python:       3.5.2-1           conda-forge
    setuptools:   23.0.0-py35_1     conda-forge
    wheel:        0.29.0-py35_0     conda-forge
    wincertstore: 0.2-py35_0        conda-forge
    zlib:         1.2.8-vc14_3      conda-forge [vc14]

Proceed ([y]/n)?

Linking packages ...
Error: ERROR: placeholder 'C:/conda/envs/_build' too short in: hdf5-1.8.17-vc14_2
```

**Comment by gillins** [comment] 2016-07-23 02:35
I can't get this to happen on my machine, but I do have a shorter prefix.

@ocefpaf you seem to have encountered this before. Seem strange it is happening - both reports above have a prefix shorter than 80 characters. Is there anything else we can try?

**Comment by ocefpaf** [comment] 2016-07-23 02:42
All I know is what @msarahan said in here:

https://github.com/conda-forge/geopandas-feedstock/issues/11#issuecomment-231433155

We are doing option (1), but we could try option (2). Not sure if that will help...

**Comment by gillins** [comment] 2016-07-23 02:44
You mean using `conda-build` 2.0? Is this an option - I mean is it released yet?

**Comment by ocefpaf** [comment] 2016-07-23 02:48
Nope. Listing all the files instead of using

```yaml
build:
  detect_binary_files_with_prefix: True
```

See: http://conda.pydata.org/docs/building/meta-yaml.html#detect-binary-files-with-prefix

**Comment by rsignell-usgs** [comment] 2016-07-26 16:04
Until this issue is resolved, can we remove the HDF5 windows binaries from the conda-forge channel?

We have a large community of non-savvy scientists that are getting failed environment builds because of this problem.   

Probably need to remove other binaries that depend on this like netcdf4, right?

**Comment by gillins** [comment] 2016-07-26 23:04
Are all failed environments using long paths in their conda installs? Or is there some other common factor? Have any of your scientists got a working environment? I'm just trying to work out a bit more about what is going on here. Weird that we are only seeing problems with `hdf5` - or are their other packages that show it?

**Comment by jakirkham** [comment] 2016-07-26 23:06
Could I ask the people running into this issue to please provide `conda info`?

**Comment by rsignell-usgs** [comment] 2016-07-27 14:03
@richardotis , I was having this problem on Windows also, but I just upgraded to the latest conda (see below) and I don't seem to have it anymore.  Can you try this and report back if it fixes the problem for you also?

```
(C:\)  conda update conda
(C:\)  conda -V
conda 4.1.11
```

**Comment by richardotis** [comment] 2016-07-27 15:19
Updating conda seems to do the trick, thanks!

AppVeyor log with successful installation: https://ci.appveyor.com/project/richardotis/pycalphad/build/job/4htrp1mj6dxywtoh

**Comment by rsignell-usgs** [comment] 2016-07-27 15:43
Wow, great!  I guess we can close this then!

**Comment by jakirkham** [comment] 2016-07-27 15:48
Glad this was an easy fix. Thanks everyone.

**Closed by jakirkham** 2016-07-27 15:48 UTC
